targets:
  $default:
    sources:
      include:
        - lib/**
      exclude:
        - lib/l10n/**
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          include_if_null: false
      freezed:
        options:
          union_key: type
          union_value_case: snake
      retrofit_generator:
        options:
          generate_example: false
          include_if_null: false
      injectable_generator:injectable_builder:
        options:
          prefer_relative_imports: true
      injectable_generator:injectable_config_builder:
        options:
          generate_for_dir:
            - lib
