arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
preferred-supported-locales: ['ar', 'en', 'ak', 'ff', 'yo', 'sw']
untranslated-messages-file: desiredFileName.txt
use-escaping: true
nullable-getter: false
synthetic-package: false
use-escalation: true