#! dart run package_rename --path="package_rename_config.yaml"
package_rename_config:
  android:
    app_name: "muein orders" # اسم التطبيق
    package_name: "com.muein.orders" # اسم الحزمة  
    override_old_package: true # لتجاهل الحزمة القديمة
    lang: "ar" # لغة التطبيق (اختياري)

  ios:
    app_name: "muein orders" # اسم التطبيق
    bundle_name: "com.muein.orders" # اسم الحزمة  
    package_name: "com.muein.orders" # اسم الحزمة

  linux:
    app_name: "muein orders" # اسم التطبيق
    package_name: "com.muein.orders" # اسم الحزمة
    exe_name: "muein_orders" # اسم ملف التنفيذ

  macos:
    app_name: "muein orders" # اسم التطبيق
    package_name: "com.muein.app.orders" # اسم الحزمة
    copyright_notice: "© 2024 IMolds" # حقوق الطبع والنشر (اختياري)

  web:
    app_name: "muein orders" # اسم التطبيق
    short_app_name: "muein_orders" # اسم التطبيق المختصر (اختياري)
    description: "muein orders App" # وصف التطبيق (اختياري)

  windows:
    app_name: "muein orders" # اسم التطبيق
    organization: "muein_orders" # اسم المؤسسة (اختياري)
    copyright_notice: "© 2026 muein_orders" # حقوق الطبع والنشر (اختياري)
    exe_name: "muein_orders" # اسم ملف التنفيذ
