import 'package:flutter/material.dart';

const Color iconColor = Color(0xffa8a09b);
const Color correctColor = Colors.green;
const Color inCorrectColor = Colors.red;
const Color naturalColor = Colors.white;
const Color backGroundColor = Colors.white;
const double oneFont = 0.03;
const double twoFont = 0.04;
const double threeFont = 0.05;
const double fourFont = 0.06;
const double fiveFont = 0.07;
const double sixFont = 0.08;
const double sevenFont = 0.09;
const double eightFont = 0.10;
const double nighnFont = 0.11;
const double tenFont = 0.12;
const double eleven = 0.13;
const double twelve = 0.14;
const double thirteen = 0.15;
