// Mocks generated by Mockito 5.4.6 from annotations
// in mubin_orders/test/unit/sign_in/bloc/sign_in_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:firebase_auth/firebase_auth.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mubin_orders/core/error/api_error_model.dart' as _i6;
import 'package:mubin_orders/features/auth/sign_in/domain/use_cases/sign_in_use_cases.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SignInUseCases].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInUseCases extends _i1.Mock implements _i3.SignInUseCases {
  MockSignInUseCases() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.User?> get onAuthStateChanged => (super.noSuchMethod(
        Invocation.getter(#onAuthStateChanged),
        returnValue: _i4.Stream<_i5.User?>.empty(),
      ) as _i4.Stream<_i5.User?>);

  @override
  _i4.Future<_i2.Either<_i6.ApiErrorModel, String>> signInWithEmailAndPassword({
    required String? email,
    required String? password,
    required bool? rememberMe,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmailAndPassword,
          [],
          {
            #email: email,
            #password: password,
            #rememberMe: rememberMe,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i6.ApiErrorModel, String>>.value(
            _FakeEither_0<_i6.ApiErrorModel, String>(
          this,
          Invocation.method(
            #signInWithEmailAndPassword,
            [],
            {
              #email: email,
              #password: password,
              #rememberMe: rememberMe,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.ApiErrorModel, String>>);

  @override
  _i4.Future<String?> getAuthToken() => (super.noSuchMethod(
        Invocation.method(
          #getAuthToken,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<_i2.Either<_i6.ApiErrorModel, void>> signOut() =>
      (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.ApiErrorModel, void>>.value(
            _FakeEither_0<_i6.ApiErrorModel, void>(
          this,
          Invocation.method(
            #signOut,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.ApiErrorModel, void>>);
}
