// Mocks generated by Mockito 5.4.6 from annotations
// in mubin_orders/test/features/auth/forgot_password/presentation/bloc/forgot_password_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mubin_orders/features/auth/forgot_password/domain/repo/forgot_password_repository.dart'
    as _i2;
import 'package:mubin_orders/features/auth/forgot_password/domain/usecases/send_password_reset_email_usecase.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeForgotPasswordRepository_0 extends _i1.SmartFake
    implements _i2.ForgotPasswordRepository {
  _FakeForgotPasswordRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SendPasswordResetEmailUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSendPasswordResetEmailUseCase extends _i1.Mock
    implements _i3.SendPasswordResetEmailUseCase {
  MockSendPasswordResetEmailUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ForgotPasswordRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeForgotPasswordRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ForgotPasswordRepository);

  @override
  _i4.Future<void> call({required String? email}) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#email: email},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
