org.gradle.jvmargs=-Xmx2048M -Dkotlin.daemon.jvm.options="-Xmx1024m"
android.useAndroidX=true
android.enableJetifier=true
$get = Get-Content .\gradle.properties -Raw
if ($get -notmatch 'kotlin.compiler.execution.strategy') {
  Add-Content .\gradle.properties "`n# Workaround: run Kotlin compiler in-process"
  Add-Content .\gradle.properties "kotlin.compiler.execution.strategy=in-process"
  Add-Content .\gradle.properties "org.gradle.jvmargs=-Xmx4096m -Dkotlin.daemon.jvm.options=`"-Xmx1024m`""
  Add-Content .\gradle.properties "org.gradle.parallel=false"
  Write-Host "-> appended kotlin execution and jvmargs to gradle.properties"
} else {
  Write-Host "-> kotlin.compiler.execution.strategy already present"
}