// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeTLNT48KM6kwGJSWnU4BSqwM4cMGsv-4',
    appId: '1:448994699498:android:74393cf2f672b119c00f93',
    messagingSenderId: '448994699498',
    projectId: 'muein-f36d0',
    storageBucket: 'muein-f36d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_CRZhhqC9LFJnb_X1-YMc6hJiQvgqHSQ',
    appId: '1:448994699498:ios:3a6767864f1ee363c00f93',
    messagingSenderId: '448994699498',
    projectId: 'muein-f36d0',
    storageBucket: 'muein-f36d0.firebasestorage.app',
    iosBundleId: 'com.example.mueinorders',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChmr66YKOYr85l0K7WqxSHP3C57o5rcho',
    appId: '1:448994699498:web:aae68046de901ba2c00f93',
    messagingSenderId: '448994699498',
    projectId: 'muein-f36d0',
    authDomain: 'muein-f36d0.firebaseapp.com',
    storageBucket: 'muein-f36d0.firebasestorage.app',
    measurementId: 'G-HQK1QRRGDB',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_CRZhhqC9LFJnb_X1-YMc6hJiQvgqHSQ',
    appId: '1:448994699498:ios:4bcd3a32f682997ec00f93',
    messagingSenderId: '448994699498',
    projectId: 'muein-f36d0',
    storageBucket: 'muein-f36d0.firebasestorage.app',
    iosBundleId: 'com.muein.app.orders',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChmr66YKOYr85l0K7WqxSHP3C57o5rcho',
    appId: '1:448994699498:web:791f7b509d66a068c00f93',
    messagingSenderId: '448994699498',
    projectId: 'muein-f36d0',
    authDomain: 'muein-f36d0.firebaseapp.com',
    storageBucket: 'muein-f36d0.firebasestorage.app',
    measurementId: 'G-4ZJRMLDFZ6',
  );

}