platform :ios, '14.0' # هنا حددنا الإصدار المطلوب لحل مشكلة workmanager

prepare_command = "node --version"

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # هذا السطر يضمن أن كل المكتبات ستعمل على إصدار 14.0
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end