# The following lines are required to link Flutter with CocoaPods
load File.join(File.dirname(File.realpath(__FILE__)), 'Flutter', 'podhelper.rb')
$FirebaseSDKVersion = '11.5.0'
platform :ios, '14.0'

target 'Runner' do
  use_frameworks! :linkage => :static

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end