name: CI/CD Pipeline
on:
    push:
        branches: [ dev, prod ]
    workflow_dispatch:
permissions:
    contents: write
jobs:
    workflows:
        uses: HishamKoptaN/flutter-devops-core/.github/workflows/00-core-main.yml@prod
        with:
            flavor: dev
            platforms: "android"
        secrets: inherit
