name: CI/CD Pipeline
# 2
on:
    push:
        branches: [ dev, prod ]
    workflow_dispatch:
permissions:
    contents: write
jobs:
    workflows:
        uses: HishamKoptaN/flutter-devops-core/.github/workflows/00-core-main.yml@prod
        with:
            flavor: dev
            platforms: "android"
        secrets:
            FIREBASE_ADMIN_SDK: ${{ secrets.FIREBASE_ADMIN_SDK }}
            SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
