name: Deploy iOS (Fastlane Legacy)
on:
  workflow_call:
    inputs:
      track:
        description: "App Store track"
        required: true
        default: "testflight"
        type: string
      action:
        description: "Action type"
        required: true
        default: "release"
        type: string
      version_name:
        description: "Version name"
        required: true
        type: string
      version_code:
        description: "Version code"
        required: true
        type: string

jobs:
  deploy-ios:
    runs-on: macos-latest
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"
          channel: "stable"
          cache: true

      - name: 📦 Get Packages
        run: flutter pub get

      - name: 💎 Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
          working-directory: ios

      - name: 📝 Create Fastlane Environment
        run: |
          cat > ios/fastlane/.env.local << EOF
          APP_IDENTIFIER=com.muein.orders
          APPLE_ID=heshamkoptan@gmail.com
          ITC_TEAM_ID=5493DS73C7
          TEAM_ID=5493DS73C7
          APP_STORE_CONNECT_KEY_ID=G2L6LRG5PK
          APP_STORE_CONNECT_ISSUER_ID=69a6de8a-717b-47e3-e053-5b8c7c11a4d1
          APP_STORE_CONNECT_KEY_PATH=./AuthKey_G2L6LRG5PK.p8
          MATCH_PASSWORD=1632001
          EOF

      - name: 📥 Install CocoaPods
        run: |
          cd ios
          pod install

      - name: 🚀 Build and Deploy
        run: |
          cd ios
          bundle exec fastlane beta_legacy
        env:
          CI: true
