name: Deploy iOS (Shorebird)
on:
  workflow_call:
    inputs:
      track:
        description: "App Store track"
        required: true
        default: "testflight"
        type: string
      action:
        description: "Action type"
        required: true
        default: "release"
        type: string
      version_name:
        description: "Version name"
        required: true
        type: string
      version_code:
        description: "Version code"
        required: true
        type: string

jobs:
  deploy-ios:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"
          channel: "stable"
          cache: true

      - run: flutter pub get

      - uses: shorebirdtech/setup-shorebird@v1
        with:
          version: latest

      - run: |
          if [ "${{ inputs.action }}" == "patch" ]; then
            shorebird patch android --release-version="${{ inputs.version_name }}"
            shorebird patch ios --release-version="${{ inputs.version_name }}"
          else
            shorebird release android --release-version="${{ inputs.version_name }}"
            shorebird release ios --release-version="${{ inputs.version_name }}"
          fi
