name: Distribute Main

on:
    push:
        branches: [dev, prod]

jobs:
    deploy_shorebird:
        uses: ./.github/workflows/deploy_shorebird.yml
        with:
            flavor: ${{ github.ref_name }}
        secrets:
            SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}

    build_installer:
        needs: deploy_shorebird
        uses: ./.github/workflows/build_installer.yml
        with:
            flavor: ${{ github.ref_name }}
            full_version: ${{ needs.deploy_shorebird.outputs.full_version }}

    github_release:
        needs: [deploy_shorebird, build_installer]
        uses: ./.github/workflows/github_release.yml
        secrets: inherit
        with:
            flavor: ${{ github.ref_name }}
            full_version: ${{ needs.deploy_shorebird.outputs.full_version }}
            version_changed: ${{ needs.deploy_shorebird.outputs.version_changed }}
            installer_name: ${{ needs.build_installer.outputs.installer_name }}

    cleanup_releases:
        needs: github_release
        uses: ./.github/workflows/cleanup_releases.yml
        secrets:
            FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
            FIREBASE_ADMIN_SDK: ${{ secrets.FIREBASE_ADMIN_SDK }}
