name: Handle Release Android
on:
  workflow_call:
    inputs:
      action:
        required: true
        type: string
        description: "Either 'release' or 'bump-and-release'"
      version_code:
        required: true
        type: string
      version_name:
        required: true
        type: string
      track:
        required: false
        type: string
        default: "internal"

jobs:
  direct-release:
    if: inputs.action == 'release'
    uses: ./.github/workflows/shorebird_release_android.yml
    with:
      version_code: ${{ inputs.version_code }}
      version_name: ${{ inputs.version_name }}
      track: ${{ inputs.track }}
    secrets: inherit

  bump-version:
    if: inputs.action == 'bump-and-release'
    uses: ./.github/workflows/bump_version_android.yml
    with:
      current_version_code: ${{ inputs.version_code }}
    secrets: inherit

  release-after-bump:
    needs: bump-version
    if: inputs.action == 'bump-and-release'
    uses: ./.github/workflows/shorebird_release_android.yml
    with:
      version_code: ${{ needs.bump-version.outputs.new_version_code }}
      version_name: ${{ inputs.version_name }}
      track: ${{ inputs.track }}
    secrets: inherit
