name: 🍏 Deploy iOS (Fastlane Match)
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
    inputs:
      track:
        description: "Deploy to"
        required: true
        default: "testflight"
        type: choice
        options:
          - testflight
          - appstore

jobs:
  deploy-ios:
    runs-on: macos-latest
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"
          channel: "stable"
          cache: true

      - name: 📦 Get Packages
        run: flutter pub get

      - name: 💎 Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
          working-directory: ios

      - name: Create Fastlane Environment
        run: |
          cat > ios/fastlane/.env.local << EOF
          APP_IDENTIFIER=com.muein.orders
          APPLE_ID=heshamkoptan@gmail.com
          ITC_TEAM_ID=5493DS73C7
          TEAM_ID=5493DS73C7
          APP_STORE_CONNECT_KEY_ID=G2L6LRG5PK
          APP_STORE_CONNECT_ISSUER_ID=69a6de8a-717b-47e3-e053-5b8c7c11a4d1
          APP_STORE_CONNECT_KEY_PATH=./AuthKey_G2L6LRG5PK.p8
          MATCH_PASSWORD=1632001
          MATCH_GIT_BASIC_AUTHORIZATION=aGVzaGFta29wdGFuOmdocF9zNlZaaFZjMlFkTjJ6V3p4TlFjMkZkZ3hC
          EOF
      - name: 📥 Install CocoaPods
        run: |
          cd ios
          pod install

      - name: 🚀 Build and Deploy
        run: |
          cd ios
          bundle exec fastlane beta
        env:
          CI: true
