name: 🍏 Deploy iOS (Legacy Fastlane)

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
    inputs:
      track:
        description: "Deploy to"
        required: true
        default: "testflight"
        type: choice
        options:
          - testflight
          - appstore

jobs:
  deploy-ios:
    runs-on: macos-latest
    env:
      ASC_JSON_KEY: ${{ secrets.ASC_JSON_KEY }}
      FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
      FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: ⚙️ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"
          channel: "stable"
          cache: true

      - name: 📦 Get Packages
        run: flutter pub get

      - name: 💎 Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
          working-directory: ios

      - name: 🔐 Setup App Store Connect
        run: echo "$ASC_JSON_KEY" >> ./ios/fastlane/store.json

      - name: 📥 Install CocoaPods
        run: |
          cd ios
          pod install

      - name: 🚀 Build and Deploy
        run: |
          cd ios
          bundle exec fastlane ios beta
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
