name: CI/CD Pipeline #11225422332135643123
on:
    push:
        branches: [ prod ]
    workflow_dispatch:
permissions:
    contents: write
jobs:
    workflows:
        uses: HishamKoptaN/flutter-devops-core/.github/workflows/00-main.yml@prod
        secrets: inherit