name: CI/CD Pipeline

on:
    push:
        branches: [ dev, prod ]
    workflow_dispatch:

permissions:
    contents: write

jobs:
    workflows:
        uses: HishamKoptaN/flutter-devops-core/.github/workflows/main.yaml@prod
        with:
            flavor: dev
            build_windows: false
        secrets: inherit
