name: CI/CD Pipeline #1122543232133123231232353214
on:
    push:
        branches: [ dev , prod ]
    workflow_dispatch:
permissions:
    contents: write
jobs:
    workflows:
        uses: HishamKoptaN/flutter-devops-core/.github/workflows/00-main.yml@prod
        secrets: inherit