name: prod_clean_releases

on:
  push:
    branches:
      - prod
jobs:
  cleanup_old_releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.PROD_CREDENTIAL_FILE_CONTENT }}

      - name: Get Access Token
        id: get_token
        run: |
          echo "token=$(gcloud auth print-access-token)" >> $GITHUB_OUTPUT

      - name: Run Cleanup Script
        env:
          FIREBASE_PROJECT_NUMBER: "999622758378"
          FIREBASE_APP_ID: ${{ secrets.PROD_FIREBASE_APP_ID }}
          GOOGLE_ACCESS_TOKEN: ${{ steps.get_token.outputs.token }}
        run: python .github/scripts/cleanup_firebase.py
