name: prod_distribute
on:
  push:
    branches:
      - prod
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "gradle"
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.0"
          channel: stable
          cache: true
      - name: Upgrade Flutter
        run: flutter upgrade
      - name: Install Dependencies
        run: flutter pub get
      - name: Build Dev v7a APK
        run: |
          flutter build apk --release \
          --flavor dev \
          --target-platform android-arm \
          --no-tree-shake-icons \
          -t lib/main.dart  # أو مسار ملف الـ main الخاص ببيئة التطوير إذا وجد
      - name: Upload to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: "armeabi-v7a"
          file: build/app/outputs/flutter-apk/app-release.apk
          releaseNotes: |
            Build: armeabi-v7a
            Message: ${{ github.event.head_commit.message }}
            Date: ${{ github.event.head_commit.author.date }}
