name: iOS Shorebird Auto-Patch
on:
  workflow_call:
    inputs:
      action:
        type: string
        required: true
jobs:
  ios:
    runs-on: macos-latest
    env:
      SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.41.2"
          channel: "stable"
          cache: true
      - run: flutter pub get
      - uses: shorebirdtech/setup-shorebird@v1
      - run: cd ios && pod install
      - run: shorebird patch ios --flavor=prod
