name: Test Google Play Connection

on:
  push:
    branches: [prod]
  workflow_dispatch:

jobs:
  test_play_auth:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # هذه الخطوة الجديدة تقوم بإنشاء ملف وهمي فارغ لكي يراه الأكشن
      - name: Create Dummy File
        run: touch dummy.aab

      - name: Authenticate and Test Google Play Connection
        uses: r0adkll/upload-google-play@v1
        with:
          packageName: com.muein.orders
          releaseFiles: dummy.aab
          track: internal
          status: draft
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          changesNotSentForReview: true