name: Test iOS Signing and Dry-Run Upload
on:
  push:
    branches:
      - prods
jobs:
  test-shorebird:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v6
      - shell: bash
        run: |